sudo: false
language: node_js
node_js:
- "5.0"
- "4.1"
- "4.0"
- "0.11"
- "0.10"
- "0.8"
deploy:
  provider: npm
  email: contact@jasonchalom.com
  api_key:
    secure:
  "on":
    tags: true
    repo: TRex22/tp-link-connector
